<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <AssemblyName>TempoTerror</AssemblyName>
    <Authors>MTVirux</Authors>
    <Description>Scrolling skill timeline overlay for FFXIV, powered by IINACT.</Description>
    <Version>1.1.0.5</Version>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="TempoTerror.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
